# ci.yml
name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: tools/ci/check_grep.sh
      - run: python3 tools/ci/check_json.py
      - run: python3 tools/ci/check_lines.py

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "LGTM!"

  test_database:
    name: "Test Database"
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:latest
        env:
          MARIADB_DATABASE: "anastasia_gamedb"
          MARIADB_ROOT_PASSWORD: "root"
        ports:
          - 3306:3306

    steps:
      - uses: actions/checkout@v4
      - run: sudo apt update && sudo apt install -y mariadb-client
      - run: cp -v testdata/SQL/* SQL/.
      - run: tools/ci/apply_sql_scripts.sh
      - run: tools/ci/check_game_database.sh

  build:
    name: "Build Docker Image"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/build-push-action@v4
        with:
          context: .
          push: false
