# ci.yml
name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: tools/ci/check_grep.sh
      - run: python3 tools/ci/check_line_endings.py

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - run: echo "LGTM!"

  test_database:
    name: 'Test Database'
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:latest  # 11.6.2 as of this writing
        env:
          MARIADB_DATABASE: "anastasia_gamedb"
          MARIADB_PASSWORD: "ss13"
          MARIADB_ROOT_PASSWORD: "root"
          MARIADB_USER: "ss13"
        ports:
          - 3306
        options: >
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-retries 10
          --health-timeout 5s
          -v ${GITHUB_WORKSPACE}/SQL:/docker-entrypoint-initdb.d:ro

    steps:
      - uses: actions/checkout@v4
      - run: sudo apt update && sudo apt install -y mariadb-client
      - run: tools/ci/check_game_database.sh

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/build-push-action@v4
        with:
          context: .
          push: false
